name: CI

on:
  pull_request:
    branches:
      - '*'

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0

      - name: Setup Current .NET SDK
        uses: actions/setup-dotnet@v1.7.2

      - name: Check Formatting
        shell: pwsh
        run: ./build.ps1 CheckFormatting

  install-tool:
    runs-on: ubuntu-latest
    needs: check-formatting

    steps:
      - uses: actions/checkout@v2.1.0

      - name: Setup Current .NET SDK
        uses: actions/setup-dotnet@v1.7.2

      - name: Install tool
        shell: pwsh
        run: ./build.ps1 InstallCliFirstTime
