name: CI

on:
  pull_request:
    branches:
      - '*'

jobs:
  run-ci:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2.1.0

      - name: Setup Current .NET SDK
        uses: actions/setup-dotnet@v1.7.2

      - name: Asd
        shell: pwsh
        run: gh --version

      - name: Run CI
        shell: pwsh
        run: ./build.ps1 RunCi --ci-build --configuration Release
