name: Update packages

on:
  schedule:
    - cron:  '0 6 * * *'
  workflow_dispatch:

jobs:
  update-packages:
    runs-on: ubuntu-latest
    name: Update dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: develop

      - name: Run Nukeeper
        shell: pwsh
        run: |
          dotnet tool install nukeeper -g
          nukeeper repo https://github.com/KuraiAndras/CsprojToAsmdef ${{ secrets.GITHUB_TOKEN }} -a 0 --targetBranch develop --maxpackageupdates 100 --consolidate
