name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0

      - name: Setup Current .NET SDK
        uses: actions/setup-dotnet@v1.7.2

      - name: Publish OpenUPM
        uses: Klemensas/action-autotag@1.2.3
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          package_root: "CsprojToAsmdef/Assets/CsprojToAsmdef"

      - name: Publish to NuGet
        shell: pwsh
        env:
          NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
        run: ./build.ps1 PushNuGet --ci-build --configuration Release --nuget-api-key "${{ secrets.NUGET_API_KEY }}"
