name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish-to-openupm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0

      - name: Publish CsprojToAsmdef to openupm
        uses: Klemensas/action-autotag@1.2.3
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          package_root: "CsprojToAsmdef/Assets/CsprojToAsmdef"

  publish-to-nuget:
    needs: publish-to-openupm
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0

      - name: Setup Current .NET SDK
        uses: actions/setup-dotnet@v1.7.2

      - name: Setup Tools .NET SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.x'

      - name: Run Nuke
        shell: pwsh
        env:
          NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
        run: ./build.ps1 PushNuGet --ci-build --configuration Release --nuget-api-key "${{ secrets.NUGET_API_KEY }}"
