name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0

      - name: Setup Current .NET SDK
        uses: actions/setup-dotnet@v1.7.2

      - name: Publish to NuGet
        shell: pwsh
        run: ./build.ps1 PushNuGet --ci-build --configuration Release --nuget-api-key "${{ secrets.NUGET_API_KEY }}" --github-token "${{ secrets.GITHUB_TOKEN }}"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
