name: Publish Tool

on:
  push:
    tags:
      - '**'

jobs:
  push-to-nuget:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0

      - name: Setup Current .NET SDK
        uses: actions/setup-dotnet@v1.7.2

      - name: Run CI
        shell: pwsh
        env:
          NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
        run: ./build.ps1 PushNuGet --ci-build --configuration Release --nuget-api-key "${{ secrets.NUGET_API_KEY }}"
